name: Conditions
on: push
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.run_id ", ${{ github.run_id }}, "contains 9"
        if: ${{ contains(github.run_id, '9') }}
      - run: exit 1
      - run: echo "Hello"
        if: ${{ failure() }}