name: Job Summaries
on: push
jobs:
  job-summaries:
    runs-on: ubuntu-latest
    steps:
      - run: |
          {
            echo "## Example Title :rocket:"
            echo "- first line"
            echo "- second line"
          } >> "${GITHUB_STEP_SUMMARY}"
